name: Pull Request
on: 
    pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --include-dev
      - name: Run ESLint
        run: npx eslint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --include-dev
      - name: Run Prettier
        run: npx prettier --check .
  
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --include-dev
      - name: Get changed files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})" >> $GITHUB_OUTPUT
      - name: Build plugins
        run: |
          npm run build -- --plugins ${{ steps.changed-files.outputs.changed_files }}